version: '3'
services:
  nginx:
    image: nginx:1.19
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    network_mode: host
    volumes:
      - ./data/artifactory:/var/opt/jfrog/artifactory
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    restart: always
    depends_on:
      - nginx
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
